### ISSUE TITLE
Does not work whatever Python version is

### ISSUE THREAD

**Issue by rboxeur** [RealDolos/mpv-setup#1]
Traceback (most recent call last):
  File "collectinfos.py", line 22, in <module>
    version = get_version(pe)
  File "collectinfos.py", line 12, in get_version
    if info.Key == b"StringFileInfo":
AttributeError: 'list' object has no attribute 'Key'

**Comment by rboxeur** [comment]
I've tested in on a recent Linux Mint  64 Bits. 
I installed all prerequisites
